### ISSUE TITLE
cowsay -n: "Undefined subroutine &main::display_usage"

### ISSUE THREAD

**Issue by ndim** [cowsay-org/cowsay#20]
This was originally reported as https://bugzilla.redhat.com/show_bug.cgi?id=2103455.

Basically, calling `cowsay -n moo` produces

```
$ cowsay --version
/usr/bin/cowsay version 3.7.0 calling Getopt::Std::getopts (version 1.13),
running under Perl version 5.34.1.
$ cowsay -n moo
Undefined subroutine &main::display_usage called at ./cowsay line 238.
$ echo s=$?
s=2
$ _
```

while the commands `cowsay moo` and `echo moo | cowsay -n` both produce cows as expected.

The `HELP_MESSAGE` output describes the `cowsay` usage as

```
Usage:

    $progname [-bdgpstwy] [-e <eyes>] [-f <cowfile> | -r [-C] ] 
        [-n] [-T <tongue>] [-W <wrapcolumn>]
        <message>
```

which means `cowsay -n <message>` should be valid `cowsay` usage.

I am not sure how much sense `cowsay -n <message>` actually makes.

Confusingly, the information about the `-n` option is not found in the man page's OPTIONS section, but is a paragraph in `DESCRIPTION`.

The `cowsay.1` man page says

> If -n is specified, there must not be any command line arguments left after all the switches have been processed.

so it appears that `cowsay` should run the `HELP_MESSAGE` function and then abort and quit the program instead of trying to call the non-existent `display_usage` function.

Also, the message `HELP_MESSAGE` prints could mention that `cowsay -n ANYTHING` is considered an error.

This problem was probably introduced in the https://github.com/cowsay-org/cowsay/commit/f863e586480d984380bfec6bbd7148895df85fdc commit.

**Comment by apjanke** [comment]
Okay, over in https://github.com/cowsay-org/cowsay/commit/0ab13e900dfb7ca96d8fd7c1819a5cb4909673c4, I fixed the busted "undefined subroutine" behavior, so now when you use `-n` incorrectly, it gives you a more reasonable help screen output, instead of a "no such perl function" "undefined subroutine" internal error.

```
[cowsay] $ ./cowsay -n moo
cowsay version 3.9.0-SNAPSHOT

Usage:

    cowsay [-bdgpstwy] [-e <eyes>] [-f <cowfile> | -r [-C] ]
        [-n] [-T <tongue>] [-W <wrapcolumn>]
        <message>
    cowsay -l    # List defined cows
    cowsay -h    # Displays this help screen

[cowsay] $ echo $?
1
[cowsay] $ echo "blah blah" | ./cowsay -n
 ___________
< blah blah >
 -----------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||
[cowsay] $
```

I still don't actually understand what `-n` is supposed to do, so I don't know if its behavior is correct in the case when you're calling it with a valid combination of command arguments.

**Comment by apjanke** [comment]
Released the basic fix in [cowsay 3.8.1](https://github.com/cowsay-org/cowsay/releases/tag/v3.8.1), so it gives a decent error message now.

I'm not sure what the right overall fix is here, but after reading the code some, I think that the `-n` option is just incompatible with messages passed on the command line (instead of via `stdin`), and combining the two should just produce an error message and exit nonzero. Objections?

**Comment by limburgher** [comment]
None. Thank you!

**Comment by apjanke** [comment]
I think this got sufficiently fixed a while back, with `cowsay -n <msg>` emitting the usage screen and exiting nonzero. Closing this ticket as Fixed. If y'all think there are more changes needed here, please drop a comment to reopen.
