### ISSUE TITLE
cowsay -h: After help message, expecting program exit but cowsay waits for input instead

### ISSUE THREAD

**Issue by ndim** [cowsay-org/cowsay#21]
When running `cowsay -h`, `cowsay` prints the help message and proceeds to wait for data on stdin, then finally prints a cow which says the data from stdin as if `cowsay` had been called.

My expectation is for `cowsay -h` to print the help message and exit the program.

As it is, `cowsay -h` does what I would expect `cowsay -h; cowsay` to do.

```
$ cowsay --version
/usr/bin/cowsay version 3.7.0 calling Getopt::Std::getopts (version 1.13),
running under Perl version 5.34.1.
$ cowsay -h
cowsay version 3.7.0

Usage:

    cowsay [-bdgpstwy] [-e <eyes>] [-f <cowfile> | -r [-C] ] 
        [-n] [-T <tongue>] [-W <wrapcolumn>]
        <message>
    cowsay -l    # List defined cows
    cowsay -h    # Displays this help screen

^C
$ cowsay -h
cowsay version 3.7.0

Usage:

    cowsay [-bdgpstwy] [-e <eyes>] [-f <cowfile> | -r [-C] ] 
        [-n] [-T <tongue>] [-W <wrapcolumn>]
        <message>
    cowsay -l    # List defined cows
    cowsay -h    # Displays this help screen

moo
^D
 _____ 
< moo >
 ----- 
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||
$ _
```

**Comment by apjanke** [comment]
Fixed in https://github.com/cowsay-org/cowsay/commit/46114bf10d40a3acd80604bc2db7a99705644842.

Your analysis here was correct. For the special case of handling `cowsay -h` (instead of `cowsay --help`), it was calling the function to display the help screen, but then not actually calling `exit()` to bail, and it fell through and moved on to the regular main case behavior, which in the absence of command-line positional arguments, read the message from stdin and displayed it.

Going out in cowsay 3.9.0.
